export default [
  { name: "Offers", url: "http://www.offers.com/" },
  { name: "Reddit", url: "https://www.reddit.com/r/freebies" },
  { name: "SD’s Forums", url: "https://slickdeals.net/forums/" },
  { name: "Dealmoon", url: "http://www.dealmoon.com/" },
  { name: "SlickDeals", url: "https://slickdeals.net/" },
  { name: "Dealsplus", url: "https://www.dealsplus.com/" },
  { name: "Deal News", url: "http://dealnews.com/" },
  { name: "RetailMeNot", url: "https://www.retailmenot.com/" },
  { name: "Dealsea", url: "http://dealsea.com/" },
  { name: "Bizrate", url: "http://www.bizrate.com/" },
  { name: "Lifehacker", url: "http://lifehacker.com/" },
  { name: "Redflagdeals", url: "http://www.redflagdeals.com/" },
  { name: "Vipon", url: "https://seller.vipon.com/" },
  { name: "Kinja", url: "http://deals.kinja.com/" },
  { name: "Hotukdeals", url: "http://www.hotukdeals.com/" },
  { name: "Dealabs", url: "http://www.dealabs.com/" },
  { name: "Mydealz", url: "http://www.mydealz.de/" },
  { name: "Techbargains", url: "http://www.techbargains.com/" },
  { name: "Tomoson", url: "https://www.tomoson.com/" },
  { name: "iLoveToReview", url: "https://www.ilovetoreview.com/" },
  { name: "UberZonClub", url: "http://www.uberzonclub.com/" },
  { name: "Snagshout", url: "https://www.snagshout.com/" },
  { name: "iReviewHome", url: "http://www.ireviewhome.com/" },
  { name: "Elitedealclub", url: "https://elitedealclub.com/" },
  { name: "Giveaway", url: "https://www.giveawayservice.com/" },
  { name: "Jumpsend", url: "https://www.jumpsend.com/" },
  { name: "GoldLeaf", url: "http://gold-leaf-group.com/" }
];
